"""add is_seed and status to writing_skills

Revision ID: 450c91999d3d
Revises: cf63c8c52527
Create Date: 2026-06-19 15:25:49.471551

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "450c91999d3d"
down_revision: str | None = "cf63c8c52527"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "writing_skills",
        sa.Column("is_seed", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "writing_skills",
        sa.Column(
            "status", sa.String(length=16), server_default="published", nullable=False
        ),
    )
    op.create_index(
        "ix_writing_skills_status", "writing_skills", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_writing_skills_status", table_name="writing_skills")
    op.drop_column("writing_skills", "status")
    op.drop_column("writing_skills", "is_seed")
    # ### end Alembic commands ###
