"""initial schema

Revision ID: cf63c8c52527
Revises:
Create Date: 2026-06-19 10:58:47.571453

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cf63c8c52527"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("google_sub", sa.Text(), nullable=True),
        sa.Column(
            "role", sa.String(length=16), server_default="viewer", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("google_sub", name=op.f("uq_users_google_sub")),
    )
    op.create_table(
        "slack_identities",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("slack_user_id", sa.Text(), nullable=False),
        sa.Column("slack_dm_channel", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_slack_identities_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_slack_identities")),
    )
    op.create_index(
        "ix_slack_identities_slack_user_id",
        "slack_identities",
        ["slack_user_id"],
        unique=False,
    )
    op.create_table(
        "social_accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "platform", sa.String(length=32), server_default="linkedin", nullable=False
        ),
        sa.Column("external_urn", sa.Text(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("access_token_enc", sa.LargeBinary(), nullable=False),
        sa.Column("refresh_token_enc", sa.LargeBinary(), nullable=True),
        sa.Column("scopes", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default="active", nullable=False
        ),
        sa.Column(
            "connected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_social_accounts_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_accounts")),
        sa.UniqueConstraint(
            "user_id", "platform", name="uq_social_accounts_user_platform"
        ),
    )
    op.create_index(
        "ix_social_accounts_expires_at", "social_accounts", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_social_accounts_status", "social_accounts", ["status"], unique=False
    )
    op.create_table(
        "writing_skills",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_writing_skills_created_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_writing_skills")),
    )
    op.create_index(
        "ix_writing_skills_is_archived", "writing_skills", ["is_archived"], unique=False
    )
    op.create_index(
        "uq_writing_skills_is_default",
        "writing_skills",
        ["is_default"],
        unique=True,
        postgresql_where="is_default",
    )
    op.create_table(
        "campaigns",
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("raw_brief", sa.Text(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("image_alt", sa.Text(), nullable=True),
        sa.Column("link", sa.Text(), nullable=True),
        sa.Column(
            "link_placement",
            sa.String(length=16),
            server_default="first_comment",
            nullable=False,
        ),
        sa.Column("hero_account_id", sa.Uuid(), nullable=True),
        sa.Column("writing_skill_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default="draft", nullable=False
        ),
        sa.Column(
            "stagger_min_seconds", sa.Integer(), server_default="600", nullable=False
        ),
        sa.Column(
            "stagger_max_seconds", sa.Integer(), server_default="1800", nullable=False
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_campaigns_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_campaigns_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["hero_account_id"],
            ["social_accounts.id"],
            name=op.f("fk_campaigns_hero_account_id_social_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["writing_skill_id"],
            ["writing_skills.id"],
            name=op.f("fk_campaigns_writing_skill_id_writing_skills"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
    )
    op.create_index(
        "ix_campaigns_created_at", "campaigns", ["created_at"], unique=False
    )
    op.create_index(
        "ix_campaigns_created_by", "campaigns", ["created_by"], unique=False
    )
    op.create_index("ix_campaigns_status", "campaigns", ["status"], unique=False)
    op.create_table(
        "posts",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("social_account_id", sa.Uuid(), nullable=True),
        sa.Column(
            "platform", sa.String(length=32), server_default="linkedin", nullable=False
        ),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("target_external_id", sa.Text(), nullable=True),
        sa.Column("angle", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("body_native", sa.Text(), nullable=True),
        sa.Column("lang", sa.String(length=16), nullable=True),
        sa.Column("link", sa.Text(), nullable=True),
        sa.Column("first_comment", sa.Text(), nullable=True),
        sa.Column("image_asset_urn", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default="pending", nullable=False
        ),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("retries", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_posts_campaign_id_campaigns"),
        ),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_accounts.id"],
            name=op.f("fk_posts_social_account_id_social_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_posts_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_posts_idempotency_key")),
    )
    op.create_index("ix_posts_campaign_id", "posts", ["campaign_id"], unique=False)
    op.create_index(
        "ix_posts_campaign_id_status", "posts", ["campaign_id", "status"], unique=False
    )
    op.create_index("ix_posts_external_id", "posts", ["external_id"], unique=False)
    op.create_index("ix_posts_user_id", "posts", ["user_id"], unique=False)
    op.create_index(
        "ix_posts_user_id_status", "posts", ["user_id", "status"], unique=False
    )
    op.create_table(
        "audit_log",
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("post_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_log_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_audit_log_campaign_id_campaigns"),
        ),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("fk_audit_log_post_id_posts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_campaign_id_created_at",
        "audit_log",
        ["campaign_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_created_at", "audit_log", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_log_created_at", table_name="audit_log")
    op.drop_index("ix_audit_log_campaign_id_created_at", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("ix_posts_user_id_status", table_name="posts")
    op.drop_index("ix_posts_user_id", table_name="posts")
    op.drop_index("ix_posts_external_id", table_name="posts")
    op.drop_index("ix_posts_campaign_id_status", table_name="posts")
    op.drop_index("ix_posts_campaign_id", table_name="posts")
    op.drop_table("posts")
    op.drop_index("ix_campaigns_status", table_name="campaigns")
    op.drop_index("ix_campaigns_created_by", table_name="campaigns")
    op.drop_index("ix_campaigns_created_at", table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(
        "uq_writing_skills_is_default",
        table_name="writing_skills",
        postgresql_where="is_default",
    )
    op.drop_index("ix_writing_skills_is_archived", table_name="writing_skills")
    op.drop_table("writing_skills")
    op.drop_index("ix_social_accounts_status", table_name="social_accounts")
    op.drop_index("ix_social_accounts_expires_at", table_name="social_accounts")
    op.drop_table("social_accounts")
    op.drop_index("ix_slack_identities_slack_user_id", table_name="slack_identities")
    op.drop_table("slack_identities")
    op.drop_table("users")
    # ### end Alembic commands ###
